import { useEffect, useState } from 'react';
import { db, PayrollRecord, Staff } from '../../db/dexie';
import { formatDate } from '../../lib/utils';

interface PayrollDetailProps {
  payrollId: string;
  onBack: () => void;
}

function formatCurrency(n: number) {
  return '$' + n.toFixed(2);
}

function printPayStub(record: PayrollRecord, member: Staff) {
  const otRate = record.hourly_rate * 1.5;
  const win = window.open('', '_blank');
  if (!win) return;
  win.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>Pay Stub — ${member.first_name} ${member.last_name}</title>
      <style>
        body { font-family: Arial, sans-serif; max-width: 600px; margin: 40px auto; padding: 24px; color: #111; border: 2px solid #0d9488; }
        .clinic-header { text-align: center; margin-bottom: 24px; border-bottom: 2px solid #0d9488; padding-bottom: 16px; }
        .clinic-name { font-size: 24px; font-weight: bold; color: #0d9488; }
        .clinic-sub { font-size: 13px; color: #666; }
        .stub-title { font-size: 16px; font-weight: bold; text-align: center; margin: 16px 0; text-transform: uppercase; letter-spacing: 1px; }
        .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; margin-bottom: 20px; font-size: 13px; }
        .info-label { color: #666; }
        .info-value { font-weight: 600; }
        table { width: 100%; border-collapse: collapse; font-size: 13px; margin: 16px 0; }
        th { background: #f0fdfa; text-align: left; padding: 8px; border: 1px solid #ccfbf1; color: #0d9488; }
        td { padding: 8px; border: 1px solid #e5e7eb; }
        .total-section { margin-top: 20px; text-align: right; font-size: 14px; }
        .net-pay { font-size: 28px; font-weight: bold; color: #0d9488; }
        .status-badge { display: inline-block; padding: 3px 10px; border-radius: 12px; font-size: 11px; font-weight: bold; }
        .paid { background: #dcfce7; color: #166534; }
        .approved { background: #fef9c3; color: #854d0e; }
        .draft { background: #f3f4f6; color: #374151; }
        .footer { margin-top: 24px; padding-top: 12px; border-top: 1px solid #ddd; font-size: 11px; color: #aaa; text-align: center; }
        @media print { body { margin: 0; border: none; } }
      </style>
    </head>
    <body>
      <div class="clinic-header">
        <div class="clinic-name">Optimum Therapy</div>
        <div class="clinic-sub">Aguadilla, Puerto Rico</div>
      </div>

      <div class="stub-title">Pay Stub</div>

      <div class="info-grid">
        <div><span class="info-label">Employee:</span></div>
        <div class="info-value">${member.first_name} ${member.last_name}</div>
        <div><span class="info-label">Role:</span></div>
        <div class="info-value">${member.role}</div>
        <div><span class="info-label">Pay Period:</span></div>
        <div class="info-value">${record.pay_period_start} to ${record.pay_period_end}</div>
        <div><span class="info-label">Status:</span></div>
        <div><span class="status-badge ${record.status}">${record.status.toUpperCase()}</span></div>
        ${record.paid_at ? `<div><span class="info-label">Paid At:</span></div><div class="info-value">${new Date(record.paid_at).toLocaleDateString()}</div>` : ''}
      </div>

      <table>
        <thead>
          <tr><th>Description</th><th>Hours</th><th>Rate</th><th>Amount</th></tr>
        </thead>
        <tbody>
          <tr>
            <td>Regular Hours</td>
            <td>${record.regular_hours.toFixed(2)}</td>
            <td>$${record.hourly_rate.toFixed(2)}/hr</td>
            <td>$${(record.regular_hours * record.hourly_rate).toFixed(2)}</td>
          </tr>
          ${record.overtime_hours > 0 ? `
          <tr>
            <td>Overtime Hours (1.5x)</td>
            <td>${record.overtime_hours.toFixed(2)}</td>
            <td>$${otRate.toFixed(2)}/hr</td>
            <td>$${(record.overtime_hours * otRate).toFixed(2)}</td>
          </tr>` : ''}
          <tr style="font-weight:bold; background:#f9fafb;">
            <td colspan="3">Gross Pay</td>
            <td>$${record.gross_pay.toFixed(2)}</td>
          </tr>
          <tr style="color:#dc2626;">
            <td colspan="3">Total Deductions</td>
            <td>- $${record.deductions.toFixed(2)}</td>
          </tr>
        </tbody>
      </table>

      <div class="total-section">
        <div style="color:#666; font-size:13px; margin-bottom:4px;">NET PAY</div>
        <div class="net-pay">$${record.net_pay.toFixed(2)}</div>
      </div>

      ${record.notes ? `<div style="margin-top:16px; font-size:12px; color:#666;"><strong>Notes:</strong> ${record.notes}</div>` : ''}

      <div class="footer">Generated by Optimum Therapy EMR &mdash; Confidential</div>
    </body>
    </html>
  `);
  win.document.close();
  win.print();
}

export function PayrollDetail({ payrollId, onBack }: PayrollDetailProps) {
  const [record, setRecord] = useState<PayrollRecord | null>(null);
  const [member, setMember] = useState<Staff | null>(null);
  const [editMode, setEditMode] = useState(false);
  const [deductions, setDeductions] = useState(0);
  const [hourlyRate, setHourlyRate] = useState(0);
  const [notes, setNotes] = useState('');
  const [saving, setSaving] = useState(false);
  const [loading, setLoading] = useState(true);

  const pid = isNaN(Number(payrollId)) ? payrollId : Number(payrollId);

  const loadRecord = async () => {
    const rec = await db.payroll.get(pid as any);
    if (rec) {
      setRecord(rec);
      setDeductions(rec.deductions);
      setHourlyRate(rec.hourly_rate);
      setNotes(rec.notes ?? '');
      const sid = isNaN(Number(rec.staff_id)) ? rec.staff_id : Number(rec.staff_id);
      const m = await db.staff.get(sid as any);
      setMember(m ?? null);
    }
    setLoading(false);
  };

  useEffect(() => { loadRecord(); }, [payrollId]);

  const recalculate = (rate: number, ded: number) => {
    if (!record) return { gross: 0, net: 0 };
    const gross = record.regular_hours * rate + record.overtime_hours * rate * 1.5;
    const net = Math.max(0, gross - ded);
    return { gross, net };
  };

  const saveEdits = async () => {
    if (!record) return;
    setSaving(true);
    const { gross, net } = recalculate(hourlyRate, deductions);
    await db.payroll.update(pid as any, {
      hourly_rate: hourlyRate,
      deductions,
      gross_pay: gross,
      net_pay: net,
      notes,
      updated_at: new Date().toISOString(),
    });
    setEditMode(false);
    setSaving(false);
    loadRecord();
  };

  const handleApprove = async () => {
    if (!record) return;
    await db.payroll.update(pid as any, {
      status: 'approved',
      approved_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    });
    loadRecord();
  };

  const handleMarkPaid = async () => {
    if (!record) return;
    await db.payroll.update(pid as any, {
      status: 'paid',
      paid_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    });
    loadRecord();
  };

  if (loading) return <div className="p-8 text-center text-gray-500">Loading...</div>;
  if (!record || !member) return (
    <div className="p-8 text-center">
      <p className="text-gray-500">Payroll record not found.</p>
      <button onClick={onBack} className="mt-4 text-teal-600 hover:underline text-sm">Go Back</button>
    </div>
  );

  const otRate = record.hourly_rate * 1.5;
  const displayRate = editMode ? hourlyRate : record.hourly_rate;
  const displayDed = editMode ? deductions : record.deductions;
  const { gross: displayGross, net: displayNet } = recalculate(displayRate, displayDed);

  const statusBadge = () => {
    if (record.status === 'draft') return <span className="bg-gray-100 text-gray-700 text-sm px-3 py-1 rounded-full">Draft</span>;
    if (record.status === 'approved') return <span className="bg-yellow-100 text-yellow-800 text-sm px-3 py-1 rounded-full">Approved</span>;
    return <span className="bg-green-100 text-green-800 text-sm px-3 py-1 rounded-full">Paid</span>;
  };

  const emailSubject = encodeURIComponent(`Pay Stub — ${record.pay_period_start} to ${record.pay_period_end}`);
  const emailBody = encodeURIComponent(`Hi ${member.first_name},\n\nPlease find your pay stub attached for the period ${record.pay_period_start} to ${record.pay_period_end}.\n\nNet Pay: $${record.net_pay.toFixed(2)}\n\nOptimum Therapy`);

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-wrap items-center gap-4">
        <button onClick={onBack} className="text-gray-500 hover:text-gray-700 flex items-center gap-1 text-sm">
          <svg xmlns="http://www.w3.org/2000/svg" className="w-4 h-4" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5" />
          </svg>
          Back to Payroll
        </button>
        <div className="flex-1">
          <h1 className="text-2xl font-bold text-gray-900">Pay Stub</h1>
          <p className="text-sm text-gray-500 mt-0.5">{member.first_name} {member.last_name} · {formatDate(record.pay_period_start)} to {formatDate(record.pay_period_end)}</p>
        </div>
        <div className="flex items-center gap-2 flex-wrap">
          {statusBadge()}
          <button
            onClick={() => printPayStub(record, member)}
            className="flex items-center gap-1.5 px-3 py-2 text-sm text-gray-600 border border-gray-300 rounded-md hover:bg-gray-50"
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="w-4 h-4" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" d="M6.72 13.829c-.24.03-.48.062-.72.096m.72-.096a42.415 42.415 0 0110.56 0m-10.56 0L6.34 18m10.94-4.171c.24.03.48.062.72.096m-.72-.096L17.66 18m0 0l.229 2.523a1.125 1.125 0 01-1.12 1.227H7.231c-.662 0-1.18-.568-1.12-1.227L6.34 18m11.318 0h1.091A2.25 2.25 0 0021 15.75V9.456c0-1.081-.768-2.015-1.837-2.175a48.055 48.055 0 00-1.913-.247M6.34 18H5.25A2.25 2.25 0 013 15.75V9.456c0-1.081.768-2.015 1.837-2.175a48.056 48.056 0 011.913-.247m10.5 0a48.536 48.536 0 00-10.5 0m10.5 0V3.375c0-.621-.504-1.125-1.125-1.125h-8.25c-.621 0-1.125.504-1.125 1.125v3.659M18 10.5h.008v.008H18V10.5zm-3 0h.008v.008H15V10.5z" />
            </svg>
            Print
          </button>
          {member.email && (
            <a
              href={`mailto:${member.email}?subject=${emailSubject}&body=${emailBody}`}
              className="flex items-center gap-1.5 px-3 py-2 text-sm text-gray-600 border border-gray-300 rounded-md hover:bg-gray-50"
            >
              <svg xmlns="http://www.w3.org/2000/svg" className="w-4 h-4" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" d="M21.75 6.75v10.5a2.25 2.25 0 01-2.25 2.25h-15a2.25 2.25 0 01-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0019.5 4.5h-15a2.25 2.25 0 00-2.25 2.25m19.5 0v.243a2.25 2.25 0 01-1.07 1.916l-7.5 4.615a2.25 2.25 0 01-2.36 0L3.32 8.91a2.25 2.25 0 01-1.07-1.916V6.75" />
              </svg>
              Email
            </a>
          )}
        </div>
      </div>

      {/* Pay Stub Card */}
      <div className="bg-white rounded-lg shadow-sm border-2 border-teal-200 overflow-hidden">
        {/* Clinic Branding */}
        <div className="bg-teal-600 text-white px-6 py-4">
          <div className="text-xl font-bold">Optimum Therapy</div>
          <div className="text-teal-100 text-sm">Aguadilla, Puerto Rico</div>
        </div>

        <div className="p-6 space-y-6">
          {/* Employee Info */}
          <div className="grid grid-cols-2 gap-4 text-sm">
            <div>
              <div className="text-gray-500 text-xs uppercase tracking-wider mb-1">Employee</div>
              <div className="font-semibold text-gray-900">{member.first_name} {member.last_name}</div>
              <div className="text-gray-500">{member.role}</div>
            </div>
            <div>
              <div className="text-gray-500 text-xs uppercase tracking-wider mb-1">Pay Period</div>
              <div className="font-semibold text-gray-900">{formatDate(record.pay_period_start)}</div>
              <div className="text-gray-500">to {formatDate(record.pay_period_end)}</div>
            </div>
          </div>

          {/* Hours & Earnings */}
          <div>
            <h3 className="text-sm font-semibold text-gray-700 uppercase tracking-wider mb-3">Hours &amp; Earnings</h3>
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-gray-50 text-xs font-medium text-gray-500 uppercase tracking-wider">
                  <th className="px-4 py-2 text-left">Description</th>
                  <th className="px-4 py-2 text-right">Hours</th>
                  <th className="px-4 py-2 text-right">Rate</th>
                  <th className="px-4 py-2 text-right">Amount</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                <tr>
                  <td className="px-4 py-3">Regular Hours</td>
                  <td className="px-4 py-3 text-right">{record.regular_hours.toFixed(2)}</td>
                  <td className="px-4 py-3 text-right">
                    {editMode ? (
                      <input
                        type="number"
                        min="0"
                        step="0.01"
                        className="w-24 p-1 border border-gray-300 rounded text-sm text-right"
                        value={hourlyRate}
                        onChange={e => setHourlyRate(parseFloat(e.target.value) || 0)}
                      />
                    ) : (
                      `$${record.hourly_rate.toFixed(2)}/hr`
                    )}
                  </td>
                  <td className="px-4 py-3 text-right">{formatCurrency(record.regular_hours * displayRate)}</td>
                </tr>
                {record.overtime_hours > 0 && (
                  <tr>
                    <td className="px-4 py-3">Overtime Hours (1.5x)</td>
                    <td className="px-4 py-3 text-right">{record.overtime_hours.toFixed(2)}</td>
                    <td className="px-4 py-3 text-right">{formatCurrency(editMode ? hourlyRate * 1.5 : otRate)}/hr</td>
                    <td className="px-4 py-3 text-right">{formatCurrency(record.overtime_hours * (editMode ? hourlyRate * 1.5 : otRate))}</td>
                  </tr>
                )}
                <tr className="bg-gray-50 font-semibold">
                  <td className="px-4 py-3" colSpan={3}>Gross Pay</td>
                  <td className="px-4 py-3 text-right">{formatCurrency(editMode ? displayGross : record.gross_pay)}</td>
                </tr>
              </tbody>
            </table>
          </div>

          {/* Deductions */}
          <div>
            <h3 className="text-sm font-semibold text-gray-700 uppercase tracking-wider mb-3">Deductions</h3>
            <div className="flex items-center justify-between bg-red-50 border border-red-100 rounded-lg px-4 py-3">
              <span className="text-sm text-gray-700">Total Deductions</span>
              {editMode ? (
                <input
                  type="number"
                  min="0"
                  step="0.01"
                  className="w-28 p-1 border border-gray-300 rounded text-sm text-right"
                  value={deductions}
                  onChange={e => setDeductions(parseFloat(e.target.value) || 0)}
                />
              ) : (
                <span className="text-sm font-semibold text-red-700">- {formatCurrency(record.deductions)}</span>
              )}
            </div>
          </div>

          {/* Notes */}
          {editMode ? (
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Notes</label>
              <textarea
                className="w-full p-2 border border-gray-300 rounded-md text-sm focus:ring-2 focus:ring-teal-500"
                rows={2}
                value={notes}
                onChange={e => setNotes(e.target.value)}
              />
            </div>
          ) : record.notes ? (
            <div className="text-sm text-gray-600">
              <span className="font-medium">Notes: </span>{record.notes}
            </div>
          ) : null}

          {/* Net Pay */}
          <div className="border-t-2 border-teal-200 pt-4 text-center">
            <div className="text-sm text-gray-500 uppercase tracking-wider mb-1">Net Pay</div>
            <div className="text-4xl font-bold text-teal-600">{formatCurrency(editMode ? displayNet : record.net_pay)}</div>
          </div>

          {/* Approval Info */}
          {(record.approved_at || record.paid_at) && (
            <div className="border-t border-gray-100 pt-4 grid grid-cols-2 gap-4 text-xs text-gray-500">
              {record.approved_at && (
                <div><span className="font-medium">Approved:</span> {new Date(record.approved_at).toLocaleString()}</div>
              )}
              {record.paid_at && (
                <div><span className="font-medium">Paid:</span> {new Date(record.paid_at).toLocaleString()}</div>
              )}
            </div>
          )}
        </div>
      </div>

      {/* Actions */}
      <div className="flex flex-wrap items-center gap-3">
        {record.status === 'draft' && !editMode && (
          <>
            <button
              onClick={() => setEditMode(true)}
              className="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50"
            >
              Edit
            </button>
            <button
              onClick={handleApprove}
              className="px-4 py-2 text-sm font-medium text-white bg-yellow-500 rounded-md hover:bg-yellow-600"
            >
              Approve
            </button>
          </>
        )}
        {record.status === 'approved' && (
          <button
            onClick={handleMarkPaid}
            className="px-4 py-2 text-sm font-medium text-white bg-green-600 rounded-md hover:bg-green-700"
          >
            Mark as Paid
          </button>
        )}
        {editMode && (
          <>
            <button
              onClick={() => { setEditMode(false); setDeductions(record.deductions); setHourlyRate(record.hourly_rate); setNotes(record.notes ?? ''); }}
              className="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50"
            >
              Cancel
            </button>
            <button
              onClick={saveEdits}
              disabled={saving}
              className="px-4 py-2 text-sm font-medium text-white bg-teal-600 rounded-md hover:bg-teal-700 disabled:opacity-50"
            >
              {saving ? 'Saving...' : 'Save Changes'}
            </button>
          </>
        )}
      </div>
    </div>
  );
}
